### ISSUE TITLE
Menubar flash on show

### ISSUE THREAD

**Issue by jamieweavis** [maxogden/menubar#229]
[//]: # "Hey there and thank you for using Menubar's issue tracker!"
[//]: # "Please fill in these information to describe your issue."

### Description

The menubar app flashes on show _after_ the first show, see [this gif](https://imgur.com/C49sEK9).

### Steps to Reproduce the Problem

1. Set the menubar `index` to a page that has a coloured background so it's easy to see the issue
2. Launch the app
3. Click the menubar app and see no flash
4. Close the menubar app
5. Click the menubar app and see a white flash

### Specifications

- Menubar version: `6.0.5`
- Platform: `macOS 10.14.4`
- Electron version: `5.0.3`

**Comment by jamieweavis** [comment]
After further investigation I've found that this isn't a problem with menubar, but with Electron instead.

I've managed to reproduce the issue with [electron/electron-quick-start](https://github.com/electron/electron-quick-start) and it looks like the issue was already tracked at https://github.com/electron/electron/issues/17942 and hopefully fixed in https://github.com/electron/electron/pull/18661 🤞 

Closing this issue! 👍

**Comment by jamieweavis** [comment]
This was fixed in [electron 5.0.8](https://github.com/electron/electron/releases/tag/v5.0.8) 🎉

**Comment by rwwagner90** [comment]
@jamieweavis I am on electron 7.1.7 and I am seeing this issue. Are we sure it was fixed?

**Comment by rwwagner90** [comment]
Seems like `app.commandLine.appendSwitch('disable-backgrounding-occluded-windows', 'true');` is needed to fix the issue still.

**Comment by jamieweavis** [comment]
I'm sure this was fixed at the time, however I'm seeing the issue again 🤔

**Comment by rwwagner90** [comment]
I think we should maybe mention adding `app.commandLine.appendSwitch('disable-backgrounding-occluded-windows', 'true');` in the README

**Comment by amaurymartiny** [comment]
+1 with the last suggestion. Would any one of you like to create a PR? I think it could go to the [tips](https://github.com/maxogden/menubar#tips) section

**Comment by rwwagner90** [comment]
@amaurymartiny I can open a PR

**Comment by rwwagner90** [comment]
https://github.com/maxogden/menubar/pull/261
